version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - redis
    networks:
      - cloudsketch-network

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:8080
    depends_on:
      - backend
    networks:
      - cloudsketch-network

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    networks:
      - cloudsketch-network

networks:
  cloudsketch-network:
    driver: bridge
